### ISSUE TITLE
UserScript Support

### ISSUE THREAD

**Issue by yujinlin0224** [Robot-Inventor/hide-view-count#23]
Can you support UserScript version that use in tampermonkey or greasemonkey? So I can use this without install a new plugin.

**Comment by Robot-Inventor** [comment]
Thank you for your feedback. I created UserScript version. You can install it from [here](https://raw.githubusercontent.com/Robot-Inventor/hide-view-count/main/index.user.js). This is my first time creating UserScript, but it should probably work!

**Comment by yujinlin0224** [comment]
It works very well, thanks you!
